ronati/terraform-provider-typesense

- .github/workflows/test.yml
> ci(test): enable test action

- .github/workflows/semver-release.yml
> ci(semantic-release): fix branch trigger for master

- .github/workflows/semver-release.yml
> fix(ci): Test write permissions to fix branch restriction

- .github/workflows/semver-release.yml
> fix(ci): Test app token to publish release to fixed branch

- .github/workflows/semver-release.yml
> fix(ci): Added missed  environment

- .github/workflows/semver-release.yml
> fix(ci): Added app token to checkout step

- .github/workflows/release-go.yml
> fix(ci): Fixed typo in release triggers

- .github/workflows/release-go.yml
- .github/workflows/semver-release.yml
> Test build

- .github/workflows/release-go.yml
> fix(ci): Removed comment

- .releaserc.json
> Test release

- .github/workflows/build-and-test.yml
- .github/workflows/semver-release.yml
- docs/resources/collection.md
> fix(ci): Added step to generate docs

- .github/workflows/semver-release.yml
> fix(ci): Fixed typo

- .goreleaser.yml
- .releaserc.json
> fix(ci): Test semantic draft release

- .releaserc.json
> fix(ci): Disabled semantic-release

- internal/provider/resource_collection.go
> fix(doc): Added description for auto type

- .releaserc.json
> fix(ci): Revert release message changes

- .releaserc.json
> fix(ci): Returned message format

- .releaserc.json
> fix(ci): Test commit format

- .github/workflows/semver-release.yml
- .releaserc.json
> fix(ci): Test action condition

- .github/workflows/sync-beta.yml
> test: Added autosync for beta branch

- .github/workflows/sync-beta.yml
> test: Test auto sync

- internal/provider/resource_collection.go
> feat: Fixed nested fields

- internal/provider/provider.go
> feat: Increase timeouts

- .github/workflows/semver-release.yml
> fix: Upgrade node version

- docs/resources/collection.md
- internal/provider/resource_collection.go
Supporting more schema parameters and field parameters for a collection
- Collection
> - symbols_to_index
> - token_separators
- Fields
>- sort
>- infix
> Supporting more schema parameters and field parameters

- .github/workflows/semver-release.yml
> fix(ci): intall terraform
